# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_INFINEON_CYW43438) 		+= cyw43438/
obj-$(CONFIG_INFINEON_CYW43455) 		+= cyw43455/
obj-$(CONFIG_INFINEON_CYW4354)  		+= cyw4354/
obj-$(CONFIG_INFINEON_CYW4373)  		+= cyw4373/
obj-$(CONFIG_INFINEON_CYW54591_SDIO) 	+= cyw54591_sdio/
obj-$(CONFIG_INFINEON_CYW54591_PCIE) 	+= cyw54591_pcie/
obj-$(CONFIG_INFINEON_CYW5557x_SDIO) 	+= cyw5557x_sdio/
obj-$(CONFIG_INFINEON_CYW5557x_PCIE) 	+= cyw5557x_pcie/

.PHONY: clean

clean:
	find . -name '*.o*' -exec rm -f {} \;
